# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cibusapp1', '0003_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='when',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'Under Preparation'), ('O', 'Dispatched'), ('D', 'Delivered')], default='P', max_length=1),
        ),
    ]
